### PR TITLE
Add timeouts to token.Wait() to prevent blocked probeing.

### LINKED ISSUE #26: Exporter does not survive an unreachable MQTT broker without being restarted
While running for days and weeks the broker the _MQTT_blackbox_exporter_ working flawlessly it stopped probing the target with only those lines in it's output / log:

```
journalctl --unit=mqtt_blackbox_exporter.service
-- Logs begin at Fr 2018-08-31 08:22:24 UTC, end at Do 2018-09-06 11:38:27 UTC. --
Aug 31 08:22:38 cvm01317 systemd[1]: Started MQTT Blackbox Exporter.
Aug 31 08:22:38 cvm01317 systemd[1]: Starting MQTT Blackbox Exporter...
Aug 31 08:22:38 cvm01317 mqtt_blackbox_exporter[864]: 08:22:38.419237 main.go:225: Starting mqtt_blackbox_exporter (build: 0.2.0-20170811-130735+b2b0651)
Sep 06 05:20:59 cvm01317 mqtt_blackbox_exporter[864]: 05:20:59.478407 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:21:30 cvm01317 mqtt_blackbox_exporter[864]: 05:21:30.057167 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:22:00 cvm01317 mqtt_blackbox_exporter[864]: 05:22:00.672315 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:22:32 cvm01317 mqtt_blackbox_exporter[864]: 05:22:32.669914 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:23:02 cvm01317 mqtt_blackbox_exporter[864]: 05:23:02.868430 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:23:33 cvm01317 mqtt_blackbox_exporter[864]: 05:23:33.161793 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:24:03 cvm01317 mqtt_blackbox_exporter[864]: 05:24:03.515896 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:24:34 cvm01317 mqtt_blackbox_exporter[864]: 05:24:34.306594 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:25:04 cvm01317 mqtt_blackbox_exporter[864]: 05:25:04.567119 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:25:35 cvm01317 mqtt_blackbox_exporter[864]: 05:25:35.482858 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:26:05 cvm01317 mqtt_blackbox_exporter[864]: 05:26:05.837598 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:26:36 cvm01317 mqtt_blackbox_exporter[864]: 05:26:36.276451 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:27:07 cvm01317 mqtt_blackbox_exporter[864]: 05:27:07.408797 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:27:38 cvm01317 mqtt_blackbox_exporter[864]: 05:27:38.204040 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:28:09 cvm01317 mqtt_blackbox_exporter[864]: 05:28:09.468270 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:28:40 cvm01317 mqtt_blackbox_exporter[864]: 05:28:40.608349 main.go:153: Network Error : %!s(<nil>)
Sep 06 05:29:10 cvm01317 mqtt_blackbox_exporter[864]: 05:29:10.846582 main.go:153: Network Error : %!s(<nil>)
```

it was still available and happily providing the _/metrics_ endpoint but those were not updated anymore. 
The _probe_mqtt_completed_total_  and _probe_mqtt_started_total_ remain static, but interestingly the__probe_mqtt_started_total_ metric was +1 of the value _probe_mqtt_completed_total_ had.

I believe the probing simply got stuck somehow, not applying some sort of timeout and recovering / retrying again for the next iteration / probing interval.

### PR DESCRIPTION
**Pull request by hikhvar**
Shoud fix #26

### CODE REVIEW

**Comment by frittentheke** [comment]
@hikhvar thanks for looking into the issue I reported!
I've been testing the blackbox exporter with your pull request included. It's been running for the last two days in three instances without issues.

One of the instances ran into a similar issue as reported before now though. The metrics stopped updating an _probe_mqtt_started_total_ was again +1 of the value _probe_mqtt_completed_total_
see:

> probe_mqtt_completed_total{broker="ssl://mqtt.example.com:1883",name="broker via LAN"} 4329
> probe_mqtt_duration_seconds_bucket{broker="ssl://mqtt.example.com:1883",name="broker via LAN",le="0.005"} 0
> probe_mqtt_duration_seconds_bucket{broker="ssl://mqtt.example.com:1883",name="broker via LAN",le="0.01"} 0
> probe_mqtt_duration_seconds_bucket{broker="ssl://mqtt.example.com:1883",name="broker via LAN",le="0.025"} 0
> probe_mqtt_duration_seconds_bucket{broker="ssl://mqtt.example.com:1883",name="broker via LAN",le="0.05"} 0
> probe_mqtt_duration_seconds_bucket{broker="ssl://mqtt.example.com:1883",name="broker via LAN",le="0.1"} 3687
> probe_mqtt_duration_seconds_bucket{broker="ssl://mqtt.example.com:1883",name="broker via LAN",le="0.25"} 4193
> probe_mqtt_duration_seconds_bucket{broker="ssl://mqtt.example.com:1883",name="broker via LAN",le="0.5"} 4258
> probe_mqtt_duration_seconds_bucket{broker="ssl://mqtt.example.com:1883",name="broker via LAN",le="1"} 4274
> probe_mqtt_duration_seconds_bucket{broker="ssl://mqtt.example.com:1883",name="broker via LAN",le="2.5"} 4325
> probe_mqtt_duration_seconds_bucket{broker="ssl://mqtt.example.com:1883",name="broker via LAN",le="5"} 4329
> probe_mqtt_duration_seconds_bucket{broker="ssl://mqtt.example.com:1883",name="broker via LAN",le="10"} 4329
> probe_mqtt_duration_seconds_bucket{broker="ssl://mqtt.example.com:1883",name="broker via LAN",le="+Inf"} 4329
> probe_mqtt_duration_seconds_sum{broker="ssl://mqtt.example.com:1883",name="broker via LAN"} 514.0778760399995
> probe_mqtt_duration_seconds_count{broker="ssl://mqtt.example.com:1883",name="broker via LAN"} 4329
> probe_mqtt_errors_total{broker="ssl://mqtt.example.com:1883",name="broker via LAN"} 0
> probe_mqtt_messages_published_total{broker="ssl://mqtt.example.com:1883",name="broker via LAN"} 43300
> probe_mqtt_messages_received_total{broker="ssl://mqtt.example.com:1883",name="broker via LAN"} 43300
> probe_mqtt_started_total{broker="ssl://mqtt.example.com:1883",name="broker via LAN"} 4330
> probe_mqtt_timeouts_total{broker="ssl://mqtt.example.com:1883",name="broker via LAN"} 0

This time there was absolutely no log output after the exporter reported successful startup.

Maybe adding a few lines of debug logging code could help to finally narrow down the last points where things could get locked up or lost waiting for things forever?

**Comment by hikhvar** [comment]
Hey @frittentheke, I added the option `-trace.enable`. This method should show up all actions taken by the mqtt library. Moreover, the blackbox exporter will now log all mqtt library errors and criticals by default.

**Comment by arnisoph** [comment]
@dirkcjelli @theinrichs FYI ^

**Comment by frittentheke** [comment]
@hikhvar Thanks a bunch. 
I rolled this new version out just now. As soon as it locks up again we should then have some more indication on where this happens in the code.

**Comment by hikhvar** [comment]
@arnoldbechtoldt PTAL . According to @frittentheke this code runs smoothly.

**Comment by arnisoph** [comment]
@hikhvar would you be so kind and cherry-pick the dep commits into a dedicated PR? So we can focus on the initial issue in this PR? :)

> According to @frittentheke this code runs smoothly.

Is this personal feedback you've received? Does it mean that the initial issue seems to be fixed?

**Comment by hikhvar** [comment]
If we cherry-pick the dep commits, this PR will not build in the CI.
Yes, this is personal feedback I recieved.

**Comment by hikhvar** [comment]
Devided this PR into Dep related changes #29 and the timeout related changes #30

**Pull request closed without merging**
