### PR TITLE
Switch to go modules

### PR DESCRIPTION
**Pull request by hikhvar**
This should be rebased onto master after #39 is merged.

### CODE REVIEW

**Review by johscheuer — COMMENTED** [review]
@hikhvar could you rebase your MR?

**Comment by arnisoph** [comment]
@johscheuer @hikhvar any plans to update/finish this PR? :D

**Comment by hikhvar** [comment]
It's rebased so go ahead an merge.

**Comment by arnisoph** [comment]
"make clean all" returns with exit code 0. LGTM & thx!

**Pull request merged**
